---
deployment:
  tasks:
    - cd frontend && npm ci
    - cd frontend && npm run build
    - mkdir -p /home/zmpwnmium/fairbis.in/magicqr/
    - rsync -a --delete frontend/dist/ /home/zmpwnmium/fairbis.in/magicqr/

